### ISSUE TITLE
Stuff for Alan to check/expand in global section

### ISSUE THREAD

**Issue by dmzuckerman** [dmzuckerman/Sampling-Uncertainty#2]
@agrossfield at some point you should look at what I've said about your block covariance method in the global sampling assessment section.

**Comment by agrossfield** [comment]
Ok, I’ll try to look later this week.

Alan

On Sep 19, 2017, at 7:10 PM, dmzuckerman <notifications@github.com<mailto:notifications@github.com>> wrote:


@agrossfield<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_agrossfield&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=qZnQh8hbJGgeRLzyj1TLEKGCn7EQH5DrUkp6MBU__J4&s=Dzqii1HVfhYK7K4VVuRa_0g8o1MXbCmJwMVWWmVKZdw&e=> at some point you should look at what I've said about your block covariance method in the global sampling assessment section.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmzuckerman_Sampling-2DUncertainty_issues_2&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=qZnQh8hbJGgeRLzyj1TLEKGCn7EQH5DrUkp6MBU__J4&s=5ZUJj_l-u0aFAjau5_bgwAGsdjx2sOFJ92zbSboG--k&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM-5F-2D8nwjIZAV7wFpYqCmlLgwiNqKqotGks5skEnbgaJpZM4PdIjQ&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=qZnQh8hbJGgeRLzyj1TLEKGCn7EQH5DrUkp6MBU__J4&s=PNojHe_09pKNzIgh6_F_boFOxF16cofC93_ZE8zbASk&e=>.

___________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu

**Comment by dmzuckerman** [comment]
@agrossfield maybe it makes more sense for you to take on the global section in the next round.  better to do a good job with quick-and-dirty now.
________________________________
