### ISSUE TITLE
The checklist itself

### ISSUE THREAD

**Issue by dmzuckerman** [dmzuckerman/Sampling-Uncertainty#29]
Have people reviewed this recently?

One question I have is whether we need to advocate that starting structures be 'representative of the true ensemble' as this suggests we need to know the answer in advance.  Is it better to say 'as diverse as possible'?  What do you think @agrossfield and @drroe ?

**Comment by agrossfield** [comment]
I wrote that, because that's the ideal. I probably should have made it clear that it's an impossible ideal.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical School


On Dec 26, 2017, at 9:24 PM, dmzuckerman <notifications@github.com<mailto:notifications@github.com>> wrote:


Have people reviewed this recently?

One question I have is whether we need to advocate that starting structures be 'representative of the true ensemble' as this suggests we need to know the answer in advance. Is it better to say 'as diverse as possible'? What do you think @agrossfield<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_agrossfield&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ujFz4Eyd-srsHFKdcSEt-zvaBvVQKdihtqX2e1fVphM&s=uABReF1LSR5ZyWM4xjHGqiN_NFFL7p4kGdMmZ8ZO1n0&e=> and @drroe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_drroe&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ujFz4Eyd-srsHFKdcSEt-zvaBvVQKdihtqX2e1fVphM&s=uSfDWfbQCvpArX2f19HmfrwEIgNkCgYmajK-kB1DYsE&e=> ?

-

**Comment by dmzuckerman** [comment]
OK, I adjusted the language in the checklist.  See if it's ok.  

@agrossfield if you want to discuss some aspects of generating diverse starting structures (e.g., automated vs. manual), feel free to add that to the planning section.

**Comment by dmzuckerman** [comment]
I added two common-sense (I think) items to the checklist.  Folks, please see if you agree.

**Comment by dwsideriusNIST** [comment]
I'm closing this issue as we seem to have iterated on a final version. Also see comment in #34
