### ISSUE TITLE
Equilibration section

### ISSUE THREAD

**Issue by dmzuckerman** [dmzuckerman/Sampling-Uncertainty#30]
Did anyone read this over besides me?  I don't too much straight MD.  @agrossfield and @drroe would you please take a look and edit as needed?  @mangiapasta do you have additional perspective?  Thank you.

**Comment by drroe** [comment]
I emphasized that the reason we discard these initial "relaxation" portions is that they tend to be non-equilibrium processes, and so should not be included when determining equilibrium properties. Also expanded the example a bit. I note that figure 2 (the RMSD plot) appears to be missing from my final PDF - not sure if the rmsd PDF in the `figures/rmsd` directory is supposed to be included or if a JPEG/PNG should be generated from `figures/rmsd/rmsd.dat`. If it's the latter, I can do this if needed.

**Comment by dmzuckerman** [comment]
@drroe - thanks a lot.  BTW I suspect I'm the one who messed up the figure (sorry!) because I'm editing in overleaf which only allows one level of subfolder.  Repair should just be a matter of fixing the path to the right directory or moving the fig to the current path.

@agrossfield would you mind reviewing equilibration section?  It's short!

**Comment by agrossfield** [comment]
Sure.  I have a few tweaks in other sections I was about to commit.

Alan


On Jan 3, 2018, at 10:50 AM, dmzuckerman <notifications@github.com<mailto:notifications@github.com>> wrote:


@drroe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_drroe&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=KhEDL2g85AUV12sSo7Nmso7ByaBdxAC0N9nx4KdBgHM&s=kEN0uqBwCAMDA5l-aPq45nxLJP8YaHurIrONErmzCT0&e=> - thanks a lot. BTW I suspect I'm the one who messed up the figure (sorry!) because I'm editing in overleaf which only allows one level of subfolder. Repair should just be a matter of fixing the path to the right directory or moving the fig to the current path.

@agrossfield<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_agrossfield&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=KhEDL2g85AUV12sSo7Nmso7ByaBdxAC0N9nx4KdBgHM&s=puBCleNTrDL3IQ-QVZPwLqXNsdy9RmwTy_CBKN-KOWs&e=> would you mind reviewing equilibration section? It's short!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmzuckerman_Sampling-2DUncertainty_issues_30-23issuecomment-2D355045880&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=KhEDL2g85AUV12sSo7Nmso7ByaBdxAC0N9nx4KdBgHM&s=u06muMVF27zh7an_24IHh-vx1Yu1rTNTN8cliGcLXWE&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM-5F-2D8kIU-2DOunWJlEq8H2Ubi0yrgHtrerks5tG6G1gaJpZM4RNHmh&d=DwMFaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=KhEDL2g85AUV12sSo7Nmso7ByaBdxAC0N9nx4KdBgHM&s=YP_3Izqjx43u09kbSguGL8cQmD5XSOgGXW5qS-VNM04&e=>.

___________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu

**Comment by mangiapasta** [comment]
I read over 2/3 of this section.  Made several edits.  I also left a few questions on RMSD.  I didn't understand that section particularly well.  I'm going to go over the coin-flip section in more detail tomorrow.  I only edited the first paragraph so far

**Comment by mangiapasta** [comment]
Sorry, I meant the previous comment to be for the quick-and-dirty section.

**Comment by mangiapasta** [comment]
Okay, I've now read the equilibration section.  I made some significant edits to a few paragraphs but kept the original text as comments in the .tex file.  So reverting should be easy if there is reason to do so.  I also put a few comments / questions near the end of the document.

**Comment by dmzuckerman** [comment]
@mangiapasta please check out my responses/changes based on your comments.
