### ISSUE TITLE
Definition of coverage factor k

### ISSUE THREAD

**Issue by agrossfield** [dmzuckerman/Sampling-Uncertainty#31]
Unless I'm missing it, we don't really define what a coverage factor is, and since it's not a common term (I'd never heard of it), we need to be very clear.  I think the best solution is an entry in the glossary, plus a line or two in the text where it's first used.

**Comment by dmzuckerman** [comment]
@dwsideriusNIST would please try to address this?  Thank you.

**Comment by dwsideriusNIST** [comment]
Yes, I'll get to this today or tomorrow.

**Comment by dwsideriusNIST** [comment]
OK, commit https://github.com/dmzuckerman/Sampling-Uncertainty/commit/be94fcbae895f78801eeee7bd4f5dfc6c51e1380 contains an new definitions section that includes one for the coverage factor. The downside is that taking the coverage factor out of the definition of the confidence interval requires a more generic definition for the CI, resulting in a more formalized definition of both the CI and the coverage factor.

Please give it a read and comment. The problem with taking the coverage factor def out of the CI definition is that I had to switch to the formalized VIM/GUM terminology of "expanded uncertainty." Otherwise, you end up with a circular definitions of the CI and the coverage factor.

**Comment by dmzuckerman** [comment]
Dan, thanks a lot.  I will take a look and see if there is a way to finesse this issue

**Comment by dwsideriusNIST** [comment]
@dmzuckerman Please do another pull before reading the new definitions - I did a slight rewrite to improve readability.

**Comment by dmzuckerman** [comment]
thanks for the heads up.  i'm in the middle of editing

**Comment by dmzuckerman** [comment]
Maybe we should switch to x_i or x_j instead of x_k and reserve k for coverage factor??

**Comment by dwsideriusNIST** [comment]
@dmzuckerman New commit addresses many of your comments, with a few replies added. Regarding the s(x_j) notation: as per my in-text comment, the "x_j" notation is used to stress that the experimental standard deviation is that it is not a property of the random variable, but is computed from the set of of experimental observations. It also follows the pedantic VIM/GUM notation.

For economy of notation, I'm actually in favor of switching to s(x), though with an explanatory footnote to clarify that restriction on the meaning of s(x).
