### ISSUE TITLE
Block averaging citation

### ISSUE THREAD

**Issue by ajschult** [dmzuckerman/Sampling-Uncertainty#4]
I was trying to write up a bit about block averaging and cite Flyvbjerg and Petersen. I was going to mention Kolafa's approach to correcting the uncertainty for correlation[1], but noticed that Kolafa's paper from 1986 (which takes block averaging as a given) predates Flyvbjerg and Petersen's paper[2] (from 1989) by 3 years.  Frenkel & Smit cite Flyvbjerg and Petersen while Allen & Tildesley (published in 1987) cite a bunch articles, the earliest of which is Friedberg and Cameron[3] from 1970, which sticks to squared errors, but otherwise describes block averaging and its utility.

Is there some reason to cite Flyvbjerg and Petersen as the originator of block averaging?  Did they add something I'm not noticing?  I'm tempted to just cite Frenkel & Smit or Allen & Tildesley.

1. http://doi.org/10.1080/00268978600102561
2. http://doi.org/10.1063/1.457480
3. http://doi.org/10.1063/1.1672907

**Comment by agrossfield** [comment]
I don't know the other refs - wouldn't be the first time the wrong people were given credit. Good catch!

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Sep 26, 2017, at 12:59 AM, Andrew Schultz <notifications@github.com<mailto:notifications@github.com>> wrote:


I was trying to write up a bit about block averaging and cite Flyvbjerg and Petersen. I was going to mention Kolafa's approach to correcting the uncertainty for correlation[1], but noticed that Kolafa's paper from 1986 (which takes block averaging as a given) predates Flyvbjerg and Petersen's paper[2] (from 1989) by 3 years. Frenkel & Smit cite Flyvbjerg and Petersen while Allen & Tildesley (published in 1987) cite a bunch articles, the earliest of which is Friedberg and Cameron[3] from 1970, which sticks to squared errors, but otherwise describes block averaging and its utility.

Is there some reason to cite Flyvbjerg and Petersen as the originator of block averaging? Did they add something I'm not noticing? I'm tempted to just cite Frenkel & Smit or Allen & Tildesley.

  1.  http://doi.org/10.1080/00268978600102561<https://urldefense.proofpoint.com/v2/url?u=http-3A__doi.org_10.1080_00268978600102561&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ub_Wn-s9pbsXks79KDh05wp-mjbiuS5ziCx2QbKaV1k&s=Ca5KxPonCWGK0WnBryGUzJWJeLX1_eaHNu_Nhjyyel4&e=>
  2.  http://doi.org/10.1063/1.457480<https://urldefense.proofpoint.com/v2/url?u=http-3A__doi.org_10.1063_1.457480&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ub_Wn-s9pbsXks79KDh05wp-mjbiuS5ziCx2QbKaV1k&s=61td8p1KAKqnyp34OrJ3kAFEnAyhCL-KvJBz_-p88Qo&e=>
  3.  http://doi.org/10.1063/1.1672907<https://urldefense.proofpoint.com/v2/url?u=http-3A__doi.org_10.1063_1.1672907&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=ub_Wn-s9pbsXks79KDh05wp-mjbiuS5ziCx2QbKaV1k&s=Nln-n3vZO14FMnjIj2GXGXB2-DiV0gVmCFzYbe2D1rs&e=>

-

**Comment by ajschult** [comment]
OK, I cited Friedberg&Cameron + Frenkel&Smit
