### ISSUE TITLE
First author of ref 50 is not boldface

### ISSUE THREAD

**Issue by ppernot** [dmzuckerman/Sampling-Uncertainty#58]

**Comment by dwsideriusNIST** [comment]
This is a known bug in the BST file (also affects ref 20). The short description is that for "edited book," the BibTeX compiler bolds either both the editor names *and* the section author names or none. Both of those references are edited books.

That said, we would like to fix it in a revision to the BibTeX style. If you have any BibTeX experience that could assist, please say so! The main thread for this bug is https://github.com/livecomsjournal/article_templates/issues/64, so I'm going to close this issue.
